{% set version = "1.5.0" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wordcloud/wordcloud-{{ version }}.tar.gz
  sha256: 6ceed30c943b49e8e8b222a4d5a6725bbeca180fada7a04c4121ed238d6896e6

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - numpy

test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli.py -h

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
