{% set version = "1.6.0" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wordcloud/wordcloud-{{ version }}.tar.gz
  sha256: 4335deb87b7cd9f8a6ce12de0257d15f14f98874f326e7a839f27b2c8ac792ca

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - numpy

test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli -h

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
