{% set name = "wordcloud" %}
{% set version = "1.9.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ac7c1378f2886d7e849600a306febd41d0d46b15ce876d665a3e549f5403b0b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
    - cython >=0.29.33
    - setuptools-scm
    - numpy {{ numpy }}
  run:
    - python
    - pillow
    # Numpy >=1.19 in specified in the upstream but numpy>2 version will be inherited from the run export
    - numpy
    - matplotlib-base >=1.5.3
    # requirements.txt
    - cython

# >       assert ret_code == expected_exit_code
# E       assert 2 == 1
{% set tests_to_deselect = "--deselect=test/test_wordcloud_cli.py::test_cli_as_executable" %}

test:
  source_files:
    - test
  imports:
    - wordcloud
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - wordcloud_cli --help
    - pytest -v test {{ tests_to_deselect }}

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A little word cloud generator in Python
  description: |
    A little word cloud generator in Python.
  dev_url: https://github.com/amueller/word_cloud
  doc_url: https://amueller.github.io/word_cloud


extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
