travis:
  secure:
    BINSTAR_TOKEN: LesL0Ak7wSc2kC8TELEDPk0iYJmAjcdr8czi4Ty8XegZYow2Y9FjxCEzua2aYSMRc6ZsUjw2z+l5vJpgCPF3s1f7zEV26gOlQ/wLeHMxPpcZhRq2vF0+qfKnIgxIG+/GmMEOkwcKe9//lb2L9qWlLeyZ2Ggc1YPbjvHWn0CGpbFaOZgCOLU1GKC7GPT6r5kuWRg2tS4Ko13vwGJviqvwnEJoS+vG8snaVk4H960AwzfFHJBkxCub6pxNRk/kXC6UZQHO36MSjAcgMQiTwNdhXozWkmuFzsGqkCqw6VL6L+etZDmY1+zxwkXJjJFuN414TEaVgbiBXKLq9xEW43xjrxiCR8GbJc8n6qlLFDUKYzXjZcU/yR5w5N0ACyFkD4w2s23fJw6CXFAwwWENfXji8nqNdl27xMGVuvte0nLl2doekWImy0FfcZBq22SIfX9jQgSLG7YEB9gwsRgfJ5wHw7RmXHCrmLsbqEYMtELKrnfYH6Ck9uo6b3n1xICwd1ZHCsPUPzqBAUNwq6TeOKeOtzq5rzHWM82Hn8O6tRpC+o252vlvsj7JbUEUTuVinOjkZh5R2GcsmvRh1ckQIXdQ+zdd1TpCqhPF74cDZgs6mlo63ElyzAYBzjnmlcEMhJwW1s3/PflkbVx21PM9oaWFAUtVVF+C1roM9qartppln4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
