travis:
  secure:
    BINSTAR_TOKEN: mF8uGQV/bZ2S+7zEx2+n7TYKLPtz/GDmwq/qjqKZ/oW7A9r2syOZyFGwvMQohtGx6Cw1Rgmmdxts0+uc3jYD06jpNnqNPrXHeV1M6fYiUsvMHxwKN4h0FwQqhOTKtHdkEHaRsfxwA32aUISSbogy1XpjTZz7aDdi8anx9aVQN0cYYdygohI1uIEvr8sWOH3dafABFCrC6MGGV7VRMZtx6WyadvR2Fjz3EVQjdUwkutGDLV5URiB6yoq1wH/Jjl8LgiGEim7dFhRt/3lgVIAWZ4WoUY0vwtEoLo9fsn8g7lFyI6CmjqUNU6vOsomgLgMrZSO8lr2ZAVbFK5dK7erWeAYJtLmAzfwfK7Hw6US3UZOivCSg4PI82RpwrUZqr6DTV8nsrdsWRSxBOg+ru0GraQ5kiyQBP68CTNfj/8t/g0qgsTSC0uJgX7BnzPx8s9nQzjGrEUIQVIm9OU3sTKNTBK6vMjUa2Jad8LdyMygci8L+GCKLiibDjgpnY7/s9N3aQ3JmmRIEzfwhfktBR8SGkefaeQrTzfN0NBsEUmSkbWMFDbsXk5AUr04mfWXlsQiG9r8FLqt6MnWTtgTXKdJqQRDOtnnD4TeHilqcaJxK3NGRvsj/53nIHxGElqJu1bjLywMOoRu8mVPmLUVAumU62U3bJex4l7buLRdE0NpjiNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
