travis:
  secure:
    BINSTAR_TOKEN: g+N7eT0MJbcv6MD1idP3nCRXzob13PEEnGw2on4BoCslVmGAQoih5wmgllFaWYYFFnw6r4aYaAkMizXi7qw9D6cVZlP2C1wDqBBPuTqohok0oUi83VkRiXKrjgdZKX5cf8TlxrNfZauauwOBglQta6hO13UnF5Zzm09RwxF0/39HQgxSZBkyqpT2mJWtmCG7PGDmaglVyyU6aSOEY2Ej7ZQIhUlhTNmdfcOcGocWLO9gjgIjuu04tYNjMM4UTKGVB75TYheyQ6kl3e5oJXgYhWsKqp8UttE7CQQU10TUOlwYVk5qkO9pQJ43FsBCGgtajKdzGijEAjGpijwJcTYWmvD24PBQ64R3hTOVNCIT6Zob8+Iy01jGiKF8br6DVsg9hX72qj924OffL8FRjbCyU8HxgaiSmbggkXk623pD7u8/3jWSs0XPs6AmRvyQ7ohZ3UFeeq9bc+wDpCcp5oDTFSvzRFtEJiELQenOODfRLA+LQheDON1kMq0rA5RNmr8duN14pepDVD7JBSBQZs3pUMbZTbY0m541VDHXbpucaR4B16KEP3nPPW7pC2jI7WXcM/I6jjNUEYqcMM3Bmm4Xrmvp419fMsYE1Q6BFuFhOxoX/psTwHn/8GHFwsbrbNS1jLmZ+wAayMct+LSdipZvK5TX2Mot8lI92GZK5CWDOlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
